name: Build Release
on:
  push:
    tags:
      - v**
permissions:
  contents: write
  actions: read
  checks: read
  deployments: read
  id-token: none
  issues: read
  discussions: read
  packages: read
  pages: read
  pull-requests: read
  repository-projects: read
  security-events: none
  statuses: read
jobs:
  build-linux:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '21'
      - run: ./gradlew clean createReleaseDistributable
      - run: pushd ./build/compose/binaries && ls -al && cd main-release && ls -al && popd
      - run: pushd ./build/compose/binaries/main-release/app && ls -al && tar -cvzf "app.tar.gz" "Giant Log Viewer" && mv "app.tar.gz" "../../../../../GiantLogViewer-${{ github.ref_name }}-linux-${{ runner.arch }}.tar.gz" && popd
      - uses: softprops/action-gh-release@v1
        with:
          files: "GiantLogViewer-${{ github.ref_name }}-linux-${{ runner.arch }}.tar.gz"
          draft: true
  build-windows:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '21'
      - run: ./gradlew clean createReleaseDistributable
      - run: pushd ./build/compose/binaries && dir && cd main-release && dir && popd
      - run: pushd ./build/compose/binaries/main-release/app && dir && tar -acf "app.zip" "Giant Log Viewer" && move "app.zip" "../../../../../GiantLogViewer-${{ github.ref_name }}-windows-${{ runner.arch }}-unsigned.zip" && popd
      - uses: softprops/action-gh-release@v1
        with:
          files: "GiantLogViewer-${{ github.ref_name }}-windows-${{ runner.arch }}-unsigned.zip"
          draft: true
      - run: mv "./GiantLogViewer-${{ github.ref_name }}-windows-${{ runner.arch }}-unsigned.zip" "artifact-unsigned.zip"
      - run: mkdir -p ./signed
      - id: upload-unsigned-artifact
        uses: actions/upload-artifact@v4
        with:
          name: "GiantLogViewer-${{ github.ref_name }}-windows-${{ runner.arch }}-unsigned-boxed"
          path: artifact-unsigned.zip
      - name: Sign the executable with SignPath
        uses: signpath/github-action-submit-signing-request@v1.1
        with:
          api-token: '${{ secrets.SIGNPATH_API_TOKEN }}'
          organization-id: '722c5ee4-3812-470e-81b7-f5af919ff54a'
          project-slug: 'giant-log-viewer'
          signing-policy-slug: 'release-signing'
          github-artifact-id: '${{ steps.upload-unsigned-artifact.outputs.artifact-id }}'
          wait-for-completion: true
          output-artifact-directory: 'signed'
          parameters: |
            version: ${{ toJSON(github.ref_name) }}
            commit: ${{ toJSON(github.sha) }}
      - run: ls -lR ./signed && mv "./signed/artifact-unsigned.zip" "GiantLogViewer-${{ github.ref_name }}-windows-${{ runner.arch }}.zip"
        shell: bash # let Windows use bash
      - uses: softprops/action-gh-release@v1
        with:
          files: "GiantLogViewer-${{ github.ref_name }}-windows-${{ runner.arch }}.zip"
          draft: true
  build-macos:
    strategy:
      matrix:
        os: [macos-15-intel, macos-14]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '21'
      - run: ./gradlew clean packageReleaseDistributionForCurrentOS
      - run: mv ./build/compose/binaries/main-release/dmg/*.dmg "./GiantLogViewer-${{ github.ref_name }}-macos-${{ runner.arch }}.dmg"
      - uses: softprops/action-gh-release@v1
        with:
          files: "./GiantLogViewer-${{ github.ref_name }}-macos-${{ runner.arch }}.dmg"
          draft: true
